apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: allocation-service-postgresql-pvc
  namespace: globeco
  labels:
    app: globeco-allocation-service-postgresql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-gp3
  resources:
    requests:
      storage: 10Gi
