apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: allocation-service-data
  namespace: globeco
  labels:
    app: globeco-allocation-service
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-gp3
  resources:
    requests:
      storage: 5Gi
