apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: execution-service-postgres-pvc
  namespace: globeco
  labels:
    app: execution-service-postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-gp3
  resources:
    requests:
      storage: 10Gi
