{{- if eq .Values.autoscaler "vpa" -}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  labels:
    app: globeco-portfolio-management-portal
  name: globeco-portfolio-management-portal-vpa
  namespace: globeco
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: globeco-portfolio-management-portal
      controlledResources:
      - cpu
      - memory
      controlledValues: RequestsOnly
      maxAllowed:
        cpu: 6000m
        memory: 6Gi
      minAllowed:
        cpu: 591m
        memory: 200Mi
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: globeco-portfolio-management-portal
  updatePolicy:
    updateMode: InPlaceOrRecreate
{{- end -}}
