{{- if eq .Values.autoscaler "vpa" -}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  labels:
    app: globeco-trade-service
  name: globeco-trade-service-vpa
  namespace: globeco
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: globeco-trade-service
      controlledResources:
      - cpu
      - memory
      controlledValues: RequestsOnly
      maxAllowed:
        cpu: 6000m
        memory: 6Gi
      minAllowed:
        cpu: 538m
        memory: 700Mi
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: globeco-trade-service
  updatePolicy:
    updateMode: InPlaceOrRecreate
{{- end -}}
