apiVersion: apps/v1
kind: Deployment
metadata:
  name: globeco-confirmation-service
  namespace: globeco
  labels:
    app: globeco-confirmation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: globeco-confirmation-service
  template:
    metadata:
      labels:
        app: globeco-confirmation-service
      annotations:
        prometheus.io/scrape: "false"
        prometheus.io/port: "8086"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: globeco-confirmation-service
          image: kasbench/globeco-confirmation-service:1.0.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
          env:
            - name: OTEL_SERVICE_NAME
              value: "globeco-confirmation-service"
            - name: OTEL_SERVICE_VERSION
              value: "1.0.0"
            - name: OTEL_SERVICE_NAMESPACE
              value: "globeco"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "otel-collector-daemonset-collector.monitoring.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=globeco-confirmation-service,service.version=1.0.0,service.namespace=globeco"
            - name: TRACING_ENABLED
              value: "true"
            - name: METRICS_ENABLED
              value: "true"
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 100Mi
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8086
            # initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 30
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8086
            # initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 30
            failureThreshold: 6
          startupProbe:
            httpGet:
              path: /health/ready
              port: 8086
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 30
