{{- if eq .Values.autoscaler "keda" -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: globeco-fix-engine-scaledobject
  namespace: globeco
  labels:
    app: globeco-fix-engine
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: globeco-fix-engine
  minReplicaCount: 0
  maxReplicaCount: 20
  # 5 minute standard cooldown policy scaled to 4:1 time compression
  cooldownPeriod: 75  
  pollingInterval: 15
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 75
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: globeco-execution-service-kafka.globeco.svc.cluster.local:9092
        topic: orders
        consumerGroup: fix_engine
        lagThreshold: "5"
        activationLagThreshold: "1"
        offsetResetPolicy: earliest
        scaleToZeroOnInvalidOffset: "true"
        allowGroupNotFound: "true" 
{{- end -}}
