{{- if eq .Values.autoscaler "vpa" -}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: globeco-fix-engine-vpa
  namespace: globeco
  labels:
    app: globeco-fix-engine
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: globeco-fix-engine
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: globeco-fix-engine
        minAllowed:
          cpu: 100m
          memory: 200Mi
        maxAllowed:
          cpu: 2000m
          memory: 2Gi
        controlledResources: ["cpu", "memory"]
        controlledValues: RequestsAndLimits
{{- end -}}
