name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    
    # This block forces the GITHUB_TOKEN to have write access for this job
    permissions:
      contents: write    # Required to create releases, tags, and push to gh-pages
      packages: write    # Good practice if publishing packages
      actions: write     # Allows the action to manage its run state

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          # Tells chart-releaser to look at the root directory instead of a "charts" folder
          charts_dir: .
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"